insert into public.mc_categories (name, sort_order) values
  ('Morning Menu', 1),
  ('Afternoon Menu', 2),
  ('All Day - Tea & Coffee', 3),
  ('All Day - Milkshakes & More', 4),
  ('Evening - Maggi', 5),
  ('Evening - Noodles', 6),
  ('Evening - Fried Rice', 7),
  ('Evening - Starters', 8),
  ('Evening - Sandwiches', 9),
  ('Evening - Toasts & Fries', 10),
  ('Dinner Items', 11)
on conflict (name) do update set sort_order = excluded.sort_order;

update public.mc_menu_items
set active = false
where (category, name) in (
  ('Breakfast', 'Idly (2 pcs)'),
  ('Breakfast', 'Masala Dosa'),
  ('Breakfast', 'Plain Dosa'),
  ('Breakfast', 'Poori Masala'),
  ('Breakfast', 'Pongal'),
  ('Lunch', 'Veg Meals'),
  ('Lunch', 'Curd Rice'),
  ('Lunch', 'Sambar Rice'),
  ('Lunch', 'Lemon Rice'),
  ('Weekend Biryani', 'Veg Biryani'),
  ('Weekend Biryani', 'Chicken Biryani'),
  ('Evening Snacks', 'Veg Fried Rice'),
  ('Evening Snacks', 'Veg Noodles'),
  ('Evening Snacks', 'Veg Sandwich'),
  ('Evening Snacks', 'Butter Toast'),
  ('Evening Snacks', 'Chocolate Milkshake'),
  ('Tea & Coffee', 'Filter Coffee'),
  ('Tea & Coffee', 'Tea')
);

delete from public.mc_categories category
where category.name in ('Breakfast', 'Lunch', 'Weekend Biryani', 'Evening Snacks', 'Tea & Coffee')
  and not exists (
    select 1 from public.mc_menu_items item
    where item.category = category.name and item.active
  );

with menu_items(name, category, price, description) as (
  values
    ('Village Dosa (2 pcs small)', 'Morning Menu', 45, null),
    ('Erra Karam Dosa', 'Morning Menu', 50, null),
    ('Egg Dosa', 'Morning Menu', 60, null),
    ('Masala Dosa', 'Morning Menu', 60, null),
    ('Open Masala Dosa', 'Morning Menu', 65, null),
    ('DG Benne Dosa (Kobbari Chutney)', 'Morning Menu', 60, null),
    ('Masal Benne Dosa', 'Morning Menu', 65, null),
    ('Podi Benne Dosa', 'Morning Menu', 65, null),
    ('Idli (3 pcs)', 'Morning Menu', 50, null),
    ('Podi Idli (3 pcs)', 'Morning Menu', 60, null),
    ('Butter Podi Idli (3 pcs)', 'Morning Menu', 65, null),
    ('Ragi Idli', 'Morning Menu', 60, null),
    ('Poori (3 pcs)', 'Morning Menu', 65, null),
    ('Single Poori (1 pc)', 'Morning Menu', 25, null),
    ('Pongal', 'Morning Menu', 65, null),
    ('Pongal Half', 'Morning Menu', 40, null),
    ('Vangi Bath', 'Afternoon Menu', 60, null),
    ('Bisi Bele Bath', 'Afternoon Menu', 65, null),
    ('Chinta Pandu Pulihora', 'Afternoon Menu', 60, null),
    ('Gongura Rice', 'Afternoon Menu', 65, null),
    ('Kobbari Anam Chicken (Fri-Sun)', 'Afternoon Menu', 149, 'Available Friday-Sunday'),
    ('Chicken Biryani (CB) (Fri-Sun)', 'Afternoon Menu', 149, 'Available Friday-Sunday'),
    ('Single CB / Kobbari Anam (Fri-Sun)', 'Afternoon Menu', 99, 'Available Friday-Sunday'),
    ('Single Tea', 'All Day - Tea & Coffee', 25, null),
    ('Full Tea', 'All Day - Tea & Coffee', 30, null),
    ('Ginger Tea', 'All Day - Tea & Coffee', 30, null),
    ('Elaichi Tea', 'All Day - Tea & Coffee', 30, null),
    ('Green Tea', 'All Day - Tea & Coffee', 30, null),
    ('Instant Coffee', 'All Day - Tea & Coffee', 30, null),
    ('Filter Coffee', 'All Day - Tea & Coffee', 30, null),
    ('Gold Coffee', 'All Day - Tea & Coffee', 40, null),
    ('Cold Coffee', 'All Day - Tea & Coffee', 50, null),
    ('Vanilla Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Chocolate Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Strawberry Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Mango Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Avocado Milkshake', 'All Day - Milkshakes & More', 120, null),
    ('Veg Maggi', 'Evening - Maggi', 59, null),
    ('Cheese Maggi', 'Evening - Maggi', 69, null),
    ('Egg Maggi', 'Evening - Maggi', 69, null),
    ('Fried Veg Maggi', 'Evening - Maggi', 69, null),
    ('Double Egg Maggi', 'Evening - Maggi', 79, null),
    ('Fried Egg Maggi', 'Evening - Maggi', 79, null),
    ('Chicken Maggi', 'Evening - Maggi', 99, null),
    ('White Sauce Maggi', 'Evening - Maggi', 99, null),
    ('Chicken Manchurian Maggi', 'Evening - Maggi', 109, null),
    ('Chicken 65 Maggi', 'Evening - Maggi', 109, null),
    ('Veg Noodles', 'Evening - Noodles', 69, null),
    ('Spicy Veg Noodles', 'Evening - Noodles', 79, null),
    ('Schezwan Veg Noodles', 'Evening - Noodles', 79, null),
    ('Singapore Veg Noodles', 'Evening - Noodles', 79, null),
    ('Spicy Egg Noodles', 'Evening - Noodles', 79, null),
    ('Schezwan Egg Noodles', 'Evening - Noodles', 89, null),
    ('Singapore Egg Noodles', 'Evening - Noodles', 89, null),
    ('Chicken Noodles', 'Evening - Noodles', 109, null),
    ('Spicy Chicken Noodles', 'Evening - Noodles', 109, null),
    ('Schezwan Chicken Noodles', 'Evening - Noodles', 119, null),
    ('Singapore Chicken Noodles', 'Evening - Noodles', 119, null),
    ('Veg Fried Rice', 'Evening - Fried Rice', 79, null),
    ('Schezwan Veg Fried Rice', 'Evening - Fried Rice', 79, null),
    ('Spicy Veg Fried Rice', 'Evening - Fried Rice', 85, null),
    ('Egg Fried Rice', 'Evening - Fried Rice', 89, null),
    ('Spicy Egg Fried Rice', 'Evening - Fried Rice', 89, null),
    ('Singapore Veg Fried Rice', 'Evening - Fried Rice', 100, null),
    ('Chicken Fried Rice', 'Evening - Fried Rice', 109, null),
    ('Schezwan Egg Fried Rice', 'Evening - Fried Rice', 110, null),
    ('Singapore Egg Fried Rice', 'Evening - Fried Rice', 110, null),
    ('Spicy Chicken Fried Rice', 'Evening - Fried Rice', 119, null),
    ('Singapore Chicken Fried Rice', 'Evening - Fried Rice', 125, null),
    ('Schezwan Chicken Fried Rice', 'Evening - Fried Rice', 130, null),
    ('Prawns Fried Rice', 'Evening - Fried Rice', 149, null),
    ('Chilli Paneer', 'Evening - Starters', 80, null),
    ('Dragon Paneer', 'Evening - Starters', 80, null),
    ('Kung Pao Paneer', 'Evening - Starters', 80, null),
    ('Chilly Egg', 'Evening - Starters', 90, null),
    ('Egg 65', 'Evening - Starters', 90, null),
    ('Chicken 555', 'Evening - Starters', 129, null),
    ('Chicken Manchuria', 'Evening - Starters', 129, null),
    ('Indo Chilli Chicken', 'Evening - Starters', 129, null),
    ('Chicken 65', 'Evening - Starters', 129, null),
    ('Dragon Chicken', 'Evening - Starters', 139, null),
    ('Chicken Majestic', 'Evening - Starters', 139, null),
    ('Egg Sandwich', 'Evening - Sandwiches', 60, null),
    ('Mumbai Style Sandwich', 'Evening - Sandwiches', 60, null),
    ('Cheese Aloo Sandwich', 'Evening - Sandwiches', 70, null),
    ('Corn Sandwich', 'Evening - Sandwiches', 70, null),
    ('Paneer Sandwich', 'Evening - Sandwiches', 80, null),
    ('Cheese Chilli Sandwich', 'Evening - Sandwiches', 80, null),
    ('Chicken Sandwich', 'Evening - Sandwiches', 90, null),
    ('High Protein Sandwich', 'Evening - Sandwiches', 90, null),
    ('Avocado Sandwich', 'Evening - Sandwiches', 100, null),
    ('Healthy Sandwich', 'Evening - Sandwiches', 110, null),
    ('Plain Toast', 'Evening - Toasts & Fries', 30, null),
    ('Egg Toast', 'Evening - Toasts & Fries', 50, null),
    ('Aloo Toast', 'Evening - Toasts & Fries', 50, null),
    ('French Toast', 'Evening - Toasts & Fries', 60, null),
    ('Japanese French Toast', 'Evening - Toasts & Fries', 100, null),
    ('French Fries', 'Evening - Toasts & Fries', 60, null),
    ('Cheesy Fries', 'Evening - Toasts & Fries', 90, null),
    ('Egg Dosa', 'Dinner Items', 60, null),
    ('Dosa Chicken', 'Dinner Items', 100, null),
    ('Poori Chicken', 'Dinner Items', 110, null)
)
update public.mc_menu_items as item
set price = menu_item.price,
    description = menu_item.description,
    active = true
from menu_items as menu_item
where item.name = menu_item.name
  and item.category = menu_item.category;

with menu_items(name, category, price, description) as (
  values
    ('Village Dosa (2 pcs small)', 'Morning Menu', 45, null),
    ('Erra Karam Dosa', 'Morning Menu', 50, null),
    ('Egg Dosa', 'Morning Menu', 60, null),
    ('Masala Dosa', 'Morning Menu', 60, null),
    ('Open Masala Dosa', 'Morning Menu', 65, null),
    ('DG Benne Dosa (Kobbari Chutney)', 'Morning Menu', 60, null),
    ('Masal Benne Dosa', 'Morning Menu', 65, null),
    ('Podi Benne Dosa', 'Morning Menu', 65, null),
    ('Idli (3 pcs)', 'Morning Menu', 50, null),
    ('Podi Idli (3 pcs)', 'Morning Menu', 60, null),
    ('Butter Podi Idli (3 pcs)', 'Morning Menu', 65, null),
    ('Ragi Idli', 'Morning Menu', 60, null),
    ('Poori (3 pcs)', 'Morning Menu', 65, null),
    ('Single Poori (1 pc)', 'Morning Menu', 25, null),
    ('Pongal', 'Morning Menu', 65, null),
    ('Pongal Half', 'Morning Menu', 40, null),
    ('Vangi Bath', 'Afternoon Menu', 60, null),
    ('Bisi Bele Bath', 'Afternoon Menu', 65, null),
    ('Chinta Pandu Pulihora', 'Afternoon Menu', 60, null),
    ('Gongura Rice', 'Afternoon Menu', 65, null),
    ('Kobbari Anam Chicken (Fri-Sun)', 'Afternoon Menu', 149, 'Available Friday-Sunday'),
    ('Chicken Biryani (CB) (Fri-Sun)', 'Afternoon Menu', 149, 'Available Friday-Sunday'),
    ('Single CB / Kobbari Anam (Fri-Sun)', 'Afternoon Menu', 99, 'Available Friday-Sunday'),
    ('Single Tea', 'All Day - Tea & Coffee', 25, null),
    ('Full Tea', 'All Day - Tea & Coffee', 30, null),
    ('Ginger Tea', 'All Day - Tea & Coffee', 30, null),
    ('Elaichi Tea', 'All Day - Tea & Coffee', 30, null),
    ('Green Tea', 'All Day - Tea & Coffee', 30, null),
    ('Instant Coffee', 'All Day - Tea & Coffee', 30, null),
    ('Filter Coffee', 'All Day - Tea & Coffee', 30, null),
    ('Gold Coffee', 'All Day - Tea & Coffee', 40, null),
    ('Cold Coffee', 'All Day - Tea & Coffee', 50, null),
    ('Vanilla Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Chocolate Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Strawberry Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Mango Milkshake', 'All Day - Milkshakes & More', 100, null),
    ('Avocado Milkshake', 'All Day - Milkshakes & More', 120, null),
    ('Veg Maggi', 'Evening - Maggi', 59, null),
    ('Cheese Maggi', 'Evening - Maggi', 69, null),
    ('Egg Maggi', 'Evening - Maggi', 69, null),
    ('Fried Veg Maggi', 'Evening - Maggi', 69, null),
    ('Double Egg Maggi', 'Evening - Maggi', 79, null),
    ('Fried Egg Maggi', 'Evening - Maggi', 79, null),
    ('Chicken Maggi', 'Evening - Maggi', 99, null),
    ('White Sauce Maggi', 'Evening - Maggi', 99, null),
    ('Chicken Manchurian Maggi', 'Evening - Maggi', 109, null),
    ('Chicken 65 Maggi', 'Evening - Maggi', 109, null),
    ('Veg Noodles', 'Evening - Noodles', 69, null),
    ('Spicy Veg Noodles', 'Evening - Noodles', 79, null),
    ('Schezwan Veg Noodles', 'Evening - Noodles', 79, null),
    ('Singapore Veg Noodles', 'Evening - Noodles', 79, null),
    ('Spicy Egg Noodles', 'Evening - Noodles', 79, null),
    ('Schezwan Egg Noodles', 'Evening - Noodles', 89, null),
    ('Singapore Egg Noodles', 'Evening - Noodles', 89, null),
    ('Chicken Noodles', 'Evening - Noodles', 109, null),
    ('Spicy Chicken Noodles', 'Evening - Noodles', 109, null),
    ('Schezwan Chicken Noodles', 'Evening - Noodles', 119, null),
    ('Singapore Chicken Noodles', 'Evening - Noodles', 119, null),
    ('Veg Fried Rice', 'Evening - Fried Rice', 79, null),
    ('Schezwan Veg Fried Rice', 'Evening - Fried Rice', 79, null),
    ('Spicy Veg Fried Rice', 'Evening - Fried Rice', 85, null),
    ('Egg Fried Rice', 'Evening - Fried Rice', 89, null),
    ('Spicy Egg Fried Rice', 'Evening - Fried Rice', 89, null),
    ('Singapore Veg Fried Rice', 'Evening - Fried Rice', 100, null),
    ('Chicken Fried Rice', 'Evening - Fried Rice', 109, null),
    ('Schezwan Egg Fried Rice', 'Evening - Fried Rice', 110, null),
    ('Singapore Egg Fried Rice', 'Evening - Fried Rice', 110, null),
    ('Spicy Chicken Fried Rice', 'Evening - Fried Rice', 119, null),
    ('Singapore Chicken Fried Rice', 'Evening - Fried Rice', 125, null),
    ('Schezwan Chicken Fried Rice', 'Evening - Fried Rice', 130, null),
    ('Prawns Fried Rice', 'Evening - Fried Rice', 149, null),
    ('Chilli Paneer', 'Evening - Starters', 80, null),
    ('Dragon Paneer', 'Evening - Starters', 80, null),
    ('Kung Pao Paneer', 'Evening - Starters', 80, null),
    ('Chilly Egg', 'Evening - Starters', 90, null),
    ('Egg 65', 'Evening - Starters', 90, null),
    ('Chicken 555', 'Evening - Starters', 129, null),
    ('Chicken Manchuria', 'Evening - Starters', 129, null),
    ('Indo Chilli Chicken', 'Evening - Starters', 129, null),
    ('Chicken 65', 'Evening - Starters', 129, null),
    ('Dragon Chicken', 'Evening - Starters', 139, null),
    ('Chicken Majestic', 'Evening - Starters', 139, null),
    ('Egg Sandwich', 'Evening - Sandwiches', 60, null),
    ('Mumbai Style Sandwich', 'Evening - Sandwiches', 60, null),
    ('Cheese Aloo Sandwich', 'Evening - Sandwiches', 70, null),
    ('Corn Sandwich', 'Evening - Sandwiches', 70, null),
    ('Paneer Sandwich', 'Evening - Sandwiches', 80, null),
    ('Cheese Chilli Sandwich', 'Evening - Sandwiches', 80, null),
    ('Chicken Sandwich', 'Evening - Sandwiches', 90, null),
    ('High Protein Sandwich', 'Evening - Sandwiches', 90, null),
    ('Avocado Sandwich', 'Evening - Sandwiches', 100, null),
    ('Healthy Sandwich', 'Evening - Sandwiches', 110, null),
    ('Plain Toast', 'Evening - Toasts & Fries', 30, null),
    ('Egg Toast', 'Evening - Toasts & Fries', 50, null),
    ('Aloo Toast', 'Evening - Toasts & Fries', 50, null),
    ('French Toast', 'Evening - Toasts & Fries', 60, null),
    ('Japanese French Toast', 'Evening - Toasts & Fries', 100, null),
    ('French Fries', 'Evening - Toasts & Fries', 60, null),
    ('Cheesy Fries', 'Evening - Toasts & Fries', 90, null),
    ('Egg Dosa', 'Dinner Items', 60, null),
    ('Dosa Chicken', 'Dinner Items', 100, null),
    ('Poori Chicken', 'Dinner Items', 110, null)
)
insert into public.mc_menu_items (name, category, price, gst_rate, description, active)
select menu_item.name, menu_item.category, menu_item.price, 5, menu_item.description, true
from menu_items as menu_item
where not exists (
  select 1 from public.mc_menu_items as existing
  where existing.name = menu_item.name and existing.category = menu_item.category
);